version: "3.9"

services:
  database:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "30000:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: sol
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME:-root}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD:-example}"

volumes:
  mongo_data: {}
