version: '1.0'

services:
  mongo_db:
    image: mongo
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: sol
      MONGO_INITDB_ROOT_USERNAME: admin
    ports:
      - "127.0.0.1:30000:27017"  # Restrito ao localhost
    volumes:
      - "${DB_DIR}:/data/db"
      - "mongo_config:/data/configdb"
      - "./mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro"
    networks:
      - sol-backend

  # server:
  #   build: .
  #   depends_on:
  #     - mongo_db
  #   networks:
  #     - sol-backend

networks:
  sol-backend:

volumes:
  mongo_config:
