services:
  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: sol-db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    ports:
      - "30000:27017"
    volumes:
      - "${DB_DIR}:/data/db"
  # server:
  #   build: .

networks:
  sol-backend:
