# Docker Compose Configuration
# visit https://docs.docker.com/compose/

services:
  # app service for your backend
  app:
    container_name: sol_backend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_NAME: ${DATABASE}         
      DATABASE_USER: ${DATABASE_USER}    
      DATABASE_PASS: ${MONGO_PASSWORD}   
      DATABASE_URI: ${NOSQL_CONNECTION_STRING}
    ports:
      - '4002:4002'
    depends_on:
      - database
    networks:
      - sol-backend

  # start the mongodb service as container
  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '30000:27017'
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE}  # Banco de dados
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}  # Usuário
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}  # Senha
      MONGO_AUTH_SOURCE: admin  # Banco de autenticação
    volumes:
      - "/home/anthonysfarias/mongodb:/data/db"
      - "./mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro"
    networks:
      - sol-backend



networks:
  sol-backend: