export enum EnviromentVariablesEnum {
  PORT = "PORT",
  ENABLE_CORS = "ENABLE_CORS",
  ENABLE_DOCS = "ENABLE_DOCS",
  NOSQL_CONNECTION_STRING = "NOSQL_CONNECTION_STRING",
  JWT_KEY = "JWT_KEY",
  JWT_REFRESH_TOKEN_KEY = "JWT_REFRESH_TOKEN_KEY",
  JWT_REFRESH_TOKEN_EXPIRATION = "JWT_REFRESH_TOKEN_EXPIRATION",
  JWT_ACCESS_TOKEN_EXPIRATION = "JWT_ACCESS_TOKEN_EXPIRATION",
  ENCRYPT_KEY = "ENCRYPT_KEY",

  SENDGRID_EMAIL_SENDER = "SENDGRID_EMAIL_SENDER",
  SENDGRID_API_KEY = "SENDGRID_API_KEY",

  PROJECT_ID = "PROJECT_ID",
  BUCKET = "BUCKET",

  REGISTRY_CONTRACT_ADDRESS = "REGISTRY_CONTRACT_ADDRESS",
  OWNER_ADDRESS = "OWNER_ADDRESS",
  ADMIN_PRIVATE_KEY = "ADMIN_PRIVATE_KEY",

  PASSWORD_SALT = "PASSWORD_SALT",
  ADMIN_DEFAULT_PASSWORD = "ADMIN_DEFAULT_PASSWORD",
  ADMIN_DEFAULT_EMAIL = "ADMIN_DEFAULT_EMAIL",

  PROVIDER = "PROVIDER",
  LACCHAIN_NODE_URL = "LACCHAIN_NODE_URL",
  BLOCKCHAIN_ACTIVE = "BLOCKCHAIN_ACTIVE",
}
