name: Staging CI/CD

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "yarn"

      - name: Instalar dependências
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Type check
        run: yarn type-check

      - name: Build
        run: yarn build

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy para Staging
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          DEPLOY_PATH: "/root/sol/sol-backend"
        run: |
          # Garante que o host remoto está no known_hosts
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

          # Envia diretório dist/
          rsync -avz ./dist/ $SSH_USER@$SSH_HOST:$DEPLOY_PATH/dist/

          # Envia arquivos do projeto
          rsync -avz yarn.lock package.json ecosystem.config.js $SSH_USER@$SSH_HOST:$DEPLOY_PATH

          # Comandos no servidor remoto
          ssh $SSH_USER@$SSH_HOST "
          cd $DEPLOY_PATH && \
          yarn install --production --frozen-lockfile && \
          pm2 reload ecosystem.config.js && \
          echo '✅ Deploy concluído!'
          "

      - name: Notificar deploy
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "🚀 Deploy para staging concluído com sucesso!"
          else
            echo "❌ Deploy para staging falhou"
            exit 1
          fi
